# Generated by Django 5.1.7 on 2025-05-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_usuario_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
